Tcp:
  Agent:
    ListenAddr: 0.0.0.0
    ListenPort: 8888
    User: admin
    Password: 123456
    
  Logging:
    Level: debug
    Path: /var/log/c2c/tcp.agent.log

Controller:
  BackendListenAddr: 0.0.0.0
  BackendListenPort: 8889
  User: admin
  Password: 123456